language: python

python:
  - "2.7"

services:
  - elasticsearch

install:
  - "pip install flake8 sphinx"
  - "python setup.py install"

before_script:
  - sleep 10 # wait for elasticsearch

script:
  - 'flake8'
  - python setup.py test
  - "python setup.py build_sphinx"
