language: python

services:
  - elasticsearch

matrix:
    include:
        - python: "2.7"
          env: TEST_SUITE=test VERSION_GEVENT=1.0.1
        - python: "2.7"
          env: TEST_SUITE=test VERSION_GEVENT=1.0.2
        - python: "2.7"
          env: TEST_SUITE=test VERSION_GEVENT=1.1.0
        - python: "2.7"
          env: TEST_SUITE=build_sphinx
        - python: "2.7"
          env: TEST_SUITE=flake

before_install:
    - '[[ -n $VERSION_GEVENT ]] && pip install --force gevent==$VERSION_GEVENT || true'

install:
    - '[[ $TEST_SUITE == flake ]] && pip install flake8 || true'
    - '[[ $TEST_SUITE != flake ]] && python setup.py install || true'
    - '[[ $TEST_SUITE == build_sphinx ]] && pip install sphinx || true'

script:
    - 'if [[ $TEST_SUITE == flake ]]; then flake8; return $?; fi'
    - 'if [[ $TEST_SUITE == test ]]; then sleep 10 && python setup.py test ; return $?; fi'
    - 'if [[ $TEST_SUITE == build_sphinx ]]; then python setup.py build_sphinx; return $?; fi'
