language: python

python:
 - 2.7

services:
  - elasticsearch

env:
    - VERSION_ES=1.x

matrix:
    fast_finish: true

    allow_failures:
        - env: VERSION_ES=2.x

    include:
        - python: "2.7"
          sudo: true
          env: VERSION_ES=2.x

        - python: "2.7"
          env: TEST_SUITE=flake

        - python: "2.7"
          env: TEST_SUITE=build_sphinx


install:
    - 'if [[ $TEST_SUITE == flake ]]; then pip install flake8; return $?; fi'
    - 'if [[ $TEST_SUITE != flake ]]; then python setup.py install; return $?; fi'
    - 'if [[ $TEST_SUITE == build_sphinx ]]; then pip install sphinx; return $?; fi'

before_script:
    - bash -x ./travis/install_dependencies.sh

script:
    - 'if [[ -z $TEST_SUITE ]]; then sleep 10; python setup.py test; return $?; fi'
    - 'if [[ $TEST_SUITE == flake ]]; then flake8; return $?; fi'
    - 'if [[ $TEST_SUITE == build_sphinx ]]; then python setup.py build_sphinx; return $?; fi'

